# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nubia/nx549j/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nubia/nx549j/proprietary/vendor/bin/gx_fpd:system/vendor/bin/gx_fpd \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/nubia/nx549j/proprietary/vendor/etc/camera/imx258_chromatix.xml:system/vendor/etc/camera/imx258_chromatix.xml \
    vendor/nubia/nx549j/proprietary/vendor/etc/camera/imx318_chromatix.xml:system/vendor/etc/camera/imx318_chromatix.xml \
    vendor/nubia/nx549j/proprietary/vendor/etc/camera/msm8953_camera_nubia549.xml:system/vendor/etc/camera/msm8953_camera_nubia549.xml \
    vendor/nubia/nx549j/proprietary/vendor/firmware/nubia_tp_boe_fw.img:system/vendor/firmware/nubia_tp_boe_fw.img \
    vendor/nubia/nx549j/proprietary/vendor/firmware/nubia_tp_jdi_fw.img:system/vendor/firmware/nubia_tp_jdi_fw.img \
    vendor/nubia/nx549j/proprietary/vendor/lib64/hw/fingerprint.default.so:system/vendor/lib64/hw/fingerprint.default.so \
    vendor/nubia/nx549j/proprietary/vendor/lib64/hw/gxfingerprint.default.so:system/vendor/lib64/hw/gxfingerprint.default.so \
    vendor/nubia/nx549j/proprietary/vendor/lib64/hw/nfc_nci.bcm2079x.default.so:system/vendor/lib64/hw/nfc_nci.bcm2079x.default.so \
    vendor/nubia/nx549j/proprietary/vendor/lib64/libfp_client.so:system/vendor/lib64/libfp_client.so \
    vendor/nubia/nx549j/proprietary/vendor/lib64/libfpnav.so:system/vendor/lib64/libfpnav.so \
    vendor/nubia/nx549j/proprietary/vendor/lib64/libfpservice.so:system/vendor/lib64/libfpservice.so \
    vendor/nubia/nx549j/proprietary/vendor/firmware/Generic_unsigned_70ms.ncd:system/vendor/firmware/Generic_unsigned_70ms.ncd \
    vendor/nubia/nx549j/proprietary/vendor/firmware/Generic_unsigned_NVM.ncd:system/vendor/firmware/Generic_unsigned_NVM.ncd \
    vendor/nubia/nx549j/proprietary/vendor/firmware/Generic_unsigned_SY.ncd:system/vendor/firmware/Generic_unsigned_SY.ncd \
    vendor/nubia/nx549j/proprietary/vendor/lib/libSonyIMX318PdafLibrary.so:system/vendor/lib/libSonyIMX318PdafLibrary.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libactuator_bu64297_nx549front.so:system/vendor/lib/libactuator_bu64297_nx549front.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libactuator_bu64297_nx549rear.so:system/vendor/lib/libactuator_bu64297_nx549rear.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_4k_preview_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_4k_preview_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_4k_video_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_4k_video_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_beauty_snapshot.so:system/vendor/lib/libchromatix_imx258_beauty_snapshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_common.so:system/vendor/lib/libchromatix_imx258_common.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx258_cpp_hfr_120.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx258_cpp_hfr_60.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_hfr_90.so:system/vendor/lib/libchromatix_imx258_cpp_hfr_90.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_liveshot.so:system/vendor/lib/libchromatix_imx258_cpp_liveshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_mtf_denoise.so:system/vendor/lib/libchromatix_imx258_cpp_mtf_denoise.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_preview.so:system/vendor/lib/libchromatix_imx258_cpp_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_snapshot.so:system/vendor/lib/libchromatix_imx258_cpp_snapshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_snapshot_beauty.so:system/vendor/lib/libchromatix_imx258_cpp_snapshot_beauty.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_video.so:system/vendor/lib/libchromatix_imx258_cpp_video.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_cpp_video_4k.so:system/vendor/lib/libchromatix_imx258_cpp_video_4k.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_default_preview_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_default_preview_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_default_video.so:system/vendor/lib/libchromatix_imx258_default_video.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_default_video_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_default_video_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_hfr_120.so:system/vendor/lib/libchromatix_imx258_hfr_120.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_hfr_120_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_hfr_120_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_hfr_60.so:system/vendor/lib/libchromatix_imx258_hfr_60.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_hfr_60_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_hfr_60_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_hfr_90.so:system/vendor/lib/libchromatix_imx258_hfr_90.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_hfr_90_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_hfr_90_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_liveshot.so:system/vendor/lib/libchromatix_imx258_liveshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_non_zsl_preview_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_non_zsl_preview_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_non_zsl_video_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_non_zsl_video_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_postproc.so:system/vendor/lib/libchromatix_imx258_postproc.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_preview.so:system/vendor/lib/libchromatix_imx258_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_snapshot.so:system/vendor/lib/libchromatix_imx258_snapshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_video_4k.so:system/vendor/lib/libchromatix_imx258_video_4k.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_zsl_preview_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_zsl_preview_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx258_zsl_video_bu64244gwz.so:system/vendor/lib/libchromatix_imx258_zsl_video_bu64244gwz.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_1080p_preview_lc898212xd.so:system/vendor/lib/libchromatix_imx318_1080p_preview_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_1080p_video_lc898212xd.so:system/vendor/lib/libchromatix_imx318_1080p_video_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_4k_preview_lc898212xd.so:system/vendor/lib/libchromatix_imx318_4k_preview_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_4k_video_lc898212xd.so:system/vendor/lib/libchromatix_imx318_4k_video_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_720p_video_lc898212xd.so:system/vendor/lib/libchromatix_imx318_720p_video_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_a3_electfno_hand.so:system/vendor/lib/libchromatix_imx318_a3_electfno_hand.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_a3_iso128_preview.so:system/vendor/lib/libchromatix_imx318_a3_iso128_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_a3_panorama.so:system/vendor/lib/libchromatix_imx318_a3_panorama.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_common.so:system/vendor/lib/libchromatix_imx318_common.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_common_iso128.so:system/vendor/lib/libchromatix_imx318_common_iso128.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_hfr_120.so:system/vendor/lib/libchromatix_imx318_cpp_hfr_120.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_hfr_60.so:system/vendor/lib/libchromatix_imx318_cpp_hfr_60.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_liveshot.so:system/vendor/lib/libchromatix_imx318_cpp_liveshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_microspur.so:system/vendor/lib/libchromatix_imx318_cpp_microspur.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_mtf_denoise.so:system/vendor/lib/libchromatix_imx318_cpp_mtf_denoise.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_panorama.so:system/vendor/lib/libchromatix_imx318_cpp_panorama.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_preview.so:system/vendor/lib/libchromatix_imx318_cpp_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_preview_nightmode.so:system/vendor/lib/libchromatix_imx318_cpp_preview_nightmode.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_preview_nightmode1.so:system/vendor/lib/libchromatix_imx318_cpp_preview_nightmode1.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_preview_profession.so:system/vendor/lib/libchromatix_imx318_cpp_preview_profession.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_snapshot.so:system/vendor/lib/libchromatix_imx318_cpp_snapshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_snapshot_nightmode.so:system/vendor/lib/libchromatix_imx318_cpp_snapshot_nightmode.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_snapshot_nightmode1.so:system/vendor/lib/libchromatix_imx318_cpp_snapshot_nightmode1.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_video.so:system/vendor/lib/libchromatix_imx318_cpp_video.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_cpp_video_4k.so:system/vendor/lib/libchromatix_imx318_cpp_video_4k.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_default_preview_lc898212xd.so:system/vendor/lib/libchromatix_imx318_default_preview_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_default_video.so:system/vendor/lib/libchromatix_imx318_default_video.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_default_video_lc898212xd.so:system/vendor/lib/libchromatix_imx318_default_video_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_fullsize_preview_lc898212xd.so:system/vendor/lib/libchromatix_imx318_fullsize_preview_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_fullsize_preview_lc898212xd_5488x3088.so:system/vendor/lib/libchromatix_imx318_fullsize_preview_lc898212xd_5488x3088.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_fullsize_preview_profession.so:system/vendor/lib/libchromatix_imx318_fullsize_preview_profession.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_fullsize_video_lc898212xd.so:system/vendor/lib/libchromatix_imx318_fullsize_video_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_hfr_120.so:system/vendor/lib/libchromatix_imx318_hfr_120.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_hfr_120_lc898212xd.so:system/vendor/lib/libchromatix_imx318_hfr_120_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_hfr_60.so:system/vendor/lib/libchromatix_imx318_hfr_60.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_hfr_60_lc898212xd.so:system/vendor/lib/libchromatix_imx318_hfr_60_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_iso128_cpp_preview.so:system/vendor/lib/libchromatix_imx318_iso128_cpp_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_iso128_cpp_snapshot.so:system/vendor/lib/libchromatix_imx318_iso128_cpp_snapshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_isp_iso128.so:system/vendor/lib/libchromatix_imx318_isp_iso128.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_isp_panorama.so:system/vendor/lib/libchromatix_imx318_isp_panorama.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_isp_quarter_preview.so:system/vendor/lib/libchromatix_imx318_isp_quarter_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_postproc.so:system/vendor/lib/libchromatix_imx318_postproc.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_preview.so:system/vendor/lib/libchromatix_imx318_preview.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_quarter_preview_lc898212xd.so:system/vendor/lib/libchromatix_imx318_quarter_preview_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_quarter_video_lc898212xd.so:system/vendor/lib/libchromatix_imx318_quarter_video_lc898212xd.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_snapshot.so:system/vendor/lib/libchromatix_imx318_snapshot.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_snapshot_nightmode.so:system/vendor/lib/libchromatix_imx318_snapshot_nightmode.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_snapshot_nightmode1.so:system/vendor/lib/libchromatix_imx318_snapshot_nightmode1.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_snapshot_profession.so:system/vendor/lib/libchromatix_imx318_snapshot_profession.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_snapshot_slowshutter.so:system/vendor/lib/libchromatix_imx318_snapshot_slowshutter.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_video_4k.so:system/vendor/lib/libchromatix_imx318_video_4k.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_zsl_preview_nightmode.so:system/vendor/lib/libchromatix_imx318_zsl_preview_nightmode.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libchromatix_imx318_zsl_preview_nightmode1.so:system/vendor/lib/libchromatix_imx318_zsl_preview_nightmode1.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libmmcamera_imx258.so:system/vendor/lib/libmmcamera_imx258.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libmmcamera_imx258_eeprom.so:system/vendor/lib/libmmcamera_imx258_eeprom.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libmmcamera_imx258_gt24c16_eeprom.so:system/vendor/lib/libmmcamera_imx258_gt24c16_eeprom.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libmmcamera_imx318.so:system/vendor/lib/libmmcamera_imx318.so \
    vendor/nubia/nx549j/proprietary/vendor/lib/libmmcamera_imx318_eeprom.so:system/vendor/lib/libmmcamera_imx318_eeprom.so
