# Copyright (C) 2018-2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/nubia/nx551j/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/nubia/nx551j/proprietary/vendor/bin/gx_fpd:$(TARGET_COPY_OUT_VENDOR)/bin/gx_fpd \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/nubia/nx551j/proprietary/vendor/etc/camera/imx258_aux_bu64297_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_aux_bu64297_chromatix.xml \
    vendor/nubia/nx551j/proprietary/vendor/etc/camera/imx258_main_bu64297_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_main_bu64297_chromatix.xml \
    vendor/nubia/nx551j/proprietary/vendor/etc/camera/msm8953_camera_nubia551.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/msm8953_camera_nubia551.xml \
    vendor/nubia/nx551j/proprietary/vendor/etc/camera/s5k3p3_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p3_chromatix.xml \
    vendor/nubia/nx551j/proprietary/vendor/firmware/SCTable.asb:$(TARGET_COPY_OUT_VENDOR)/firmware/SCTable.asb \
    vendor/nubia/nx551j/proprietary/vendor/firmware/TBM_D2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/TBM_D2.bin \
    vendor/nubia/nx551j/proprietary/vendor/firmware/miniBoot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/miniBoot.bin \
    vendor/nubia/nx551j/proprietary/vendor/firmware/nubia_tp_1302_jdi_fw.img:$(TARGET_COPY_OUT_VENDOR)/firmware/nubia_tp_1302_jdi_fw.img \
    vendor/nubia/nx551j/proprietary/vendor/firmware/tas2555_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2555_uCDSP.bin \
    vendor/nubia/nx551j/proprietary/vendor/lib64/hw/fingerprint.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.default.so \
    vendor/nubia/nx551j/proprietary/vendor/lib64/hw/gxfingerprint.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gxfingerprint.default.so \
    vendor/nubia/nx551j/proprietary/vendor/lib64/libfp_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfp_client.so \
    vendor/nubia/nx551j/proprietary/vendor/lib64/libfpservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfpservice.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libactuator_bu64297_aux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64297_aux.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libactuator_bu64297_main.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64297_main.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_4k_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_4k_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_4k_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_4k_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_default_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_default_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_depth_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_depth_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_electfno_hand.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_electfno_hand.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_fusion_mode_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_fusion_mode_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_iso128_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_iso128_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_panorama.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_slowshutter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_slowshutter.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_zsl_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_zsl_preview_electfno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_zsl_preview_electfno.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_zsl_preview_lightdraw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_zsl_preview_lightdraw.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_a3_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_a3_zsl_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_common.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_common_iso128.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_common_iso128.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_iso128_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_iso128_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_iso128_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_iso128_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_liveshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_microspur.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_microspur.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_panorama.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_snapshot_electfno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_snapshot_electfno.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_snapshot_lightdraw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_snapshot_lightdraw.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_cpp_video_4k.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_fusion_mode_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_fusion_mode_common.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_default_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_iso128.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_iso128.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_liveshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_panorama.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_depth.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_depth.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_electfno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_electfno.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_fusion_mode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_fusion_mode.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_lightdraw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_lightdraw.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_slowshutter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_snapshot_slowshutter.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_isp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_isp_video_4k.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_aux_bu64297_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_aux_bu64297_postproc.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_4k_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_4k_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_4k_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_4k_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_default_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_default_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_depth_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_depth_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_electfno_hand.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_electfno_hand.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_fusion_mode_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_fusion_mode_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_iso128_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_iso128_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_panorama.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_slowshutter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_slowshutter.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_zsl_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_zsl_preview_electfno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_zsl_preview_electfno.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_zsl_preview_lightdraw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_zsl_preview_lightdraw.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_a3_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_a3_zsl_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_common.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_common_iso128.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_common_iso128.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_iso128_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_iso128_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_iso128_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_iso128_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_liveshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_microspur.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_microspur.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_mtf_denoise.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_mtf_denoise.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_panorama.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_preview_profession.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_preview_profession.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_electfno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_electfno.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_fusion_h.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_fusion_h.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_fusion_m.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_fusion_m.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_lightdraw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_snapshot_lightdraw.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_cpp_video_4k.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_fusion_mode_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_fusion_mode_common.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_default_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_iso128.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_iso128.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_liveshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_panorama.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_snapshot_depth.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_snapshot_depth.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_snapshot_electfno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_snapshot_electfno.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_snapshot_fusion_mode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_snapshot_fusion_mode.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_snapshot_lightdraw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_snapshot_lightdraw.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_snapshot_slowshutter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_snapshot_slowshutter.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_isp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_isp_video_4k.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_postproc.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_preview_profession.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_preview_profession.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_imx258_main_bu64297_snapshot_profession.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_main_bu64297_snapshot_profession.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_common.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_hfr_90.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_liveshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_mtf_denoise.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_mtf_denoise.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_cpp_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_default_preview_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_default_preview_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_default_video.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_default_video_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_default_video_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_hfr_120.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_hfr_120_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_hfr_120_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_hfr_60.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_hfr_60_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_hfr_60_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_hfr_90.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_hfr_90_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_hfr_90_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_postproc.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_preview.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_snapshot.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_zsl_preview_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_zsl_preview_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libchromatix_s5k3p3_zsl_video_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_zsl_video_dw9800.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera_imx258_aux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx258_aux.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera_imx258_bu64297_aux_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx258_bu64297_aux_eeprom.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera_imx258_bu64297_main_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx258_bu64297_main_eeprom.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera_imx258_main.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx258_main.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera_s5k3p3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3p3.so \
    vendor/nubia/nx551j/proprietary/vendor/lib/libmmcamera_s5k3p3_front_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3p3_front_eeprom.so
